services:
  - type: web
    name: chickcare
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      # Check if test.sql exists and then run it
      if [ -f test.sql ]; then
        psql $DATABASE_URL -f test.sql
      fi
    startCommand: python ChickCare.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chickcare-db
          property: connectionString

databases:
  - name: chickcare-db
    databaseName: chickcare
    user: chickcare
    plan: free
